name: context
on: 
  repository_dispatch:
    types: [clone_template]
  push:
    paths:
      - "**.go"
jobs:
  clone-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import privatekey to golang
        run: |
          auth_key=${SSH_AUTHKEY}
          cat $auth_key
          sed -i "s/pass_auth/'${SSH_PASS_AUTHKEY}'/g"  docs/clone_test_postman.go
          sed -i -e "s/private_key/$auth_key/g"  docs/clone_test_postman.go
        env:
          SSH_PASSPHRASE: ${{ secrets.TEST_SECRET }}
          SSH_AUTHKEY: ${{ secrets.AUTHKEY }}
          SSH_PASS_AUTHKEY: ${{ secrets.PASS_AUTHKEY }}
      - name: Sed env from postman 
        run: |
          sed -i "0,/srcid_template/s//'${ID_TEMPLATE}'/g"  docs/clone_test_postman.go
          sed -i "s/node_template/'$NODE_TEMPLATE'/g"  docs/clone_test_postman.go
          sed -i "s/id_template/'$ID_NEW_TEMPLATE'/g"  docs/clone_test_postman.go
          sed -i "s/'//g" docs/clone_test_postman.go
        env: 
          ID_TEMPLATE: ${{ github.event.client_payload.id}}\
          NODE_TEMPLATE: ${{ github.event.client_payload.node}}\
          ID_NEW_TEMPLATE: ${{ github.event.client_payload.new_id}}\
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go version
      - run: go env -w GO111MODULE=off
      - run: go get -u github.com/helloyi/go-sshclient
      - run: go run 'docs/clone_test_postman.go'
