name: context
on: 
  repository_dispatch:
    types: [clone_template]
  push:
    paths:
      - "**.go"
  workflow_dispatch:
jobs:
  clone-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import private key
        run: |
          sed -i "s/pass_auth/'$SSH_PASS_AUTHKEY'/g"  docs/clone_test_postman.go
          echo "$SSH_AUTHKEY" > docs/id_rsa
        env:
          SSH_AUTHKEY: ${{ secrets.AUTHKEY }}
          SSH_PASS_AUTHKEY: ${{ secrets.PASS_AUTHKEY }}
      - name: Sed env from postman 
        run: |
          sed -i "0,/srcid_template/s//'${ID_TEMPLATE}'/g"  docs/clone_test_postman.go
          sed -i "s/ip_host/'$IP_HOST'/g"  docs/clone_test_postman.go
          sed -i "s/node_template/'$NODE_TEMPLATE'/g"  docs/clone_test_postman.go
          sed -i "s/id_template/'$ID_NEW_TEMPLATE'/g"  docs/clone_test_postman.go
          sed -i "s/'//g" docs/clone_test_postman.go
        env: 
          IP_HOST: ${{ github.event.client_payload.host}}\
          ID_TEMPLATE: ${{ github.event.client_payload.id}}\
          NODE_TEMPLATE: ${{ github.event.client_payload.node}}\
          ID_NEW_TEMPLATE: ${{ github.event.client_payload.new_id}}\
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go version
      - run: go env -w GO111MODULE=off
      - run: go get -u github.com/helloyi/go-sshclient
      - run: go run 'docs/clone_test_postman.go'
