name: context
on: 
  repository_dispatch:
    types: [clone_template]
  push:
    paths:
      - "**.go"
jobs:
  one:
    if: github.branches == 'feature'
    runs-on: ubuntu-latest
    steps: 
      - name: Dump github context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump RUNNER context
        env: 
          RUNNER_CONTEXT: ${{ toJson(github) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump STEPS context
        env: 
          STEPS_CONTEXT: ${{ toJson(github) }}
        run: echo "$STEPS_CONTEXT"
      - name: dump TEST_SECRET
        run: echo ${{ secrets.TEST_SECRET }}
      - name: list file in folder docs
        run: ls -la
  clone-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sed env from postman 
        run: |
          sed -i 's/abcd/'$SSH_PASSPHRASE'/g'  docs/hello_world.go
          sed -i '0,/id_template/s//"$ID_TEMPLATE"/g'  docs/hello_world.go
          sed -i 's/node_template/"$NODE_TEMPLATE"/g'  docs/hello_world.go
          sed -i 's/newid_template/"$ID_NEW_TEMPLATE"/g'  docs/hello_world.go
          cat docs/hello_world.go
        env: 
          SSH_PASSPHRASE: ${{ secrets.TEST_SECRET }}
          ID_TEMPLATE: ${{ github.event.client_payload.id}}\
          NODE_TEMPLATE: ${{ github.event.client_payload.node}}\
          ID_NEW_TEMPLATE: ${{ github.event.client_payload.new_id}}\
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go version
      - run: go env -w GO111MODULE=off
      - run: go get -u github.com/helloyi/go-sshclient
      - run: go run 'docs/hello_world.go'
