name: context
on: 
  repository_dispatch:
    types: [dump-context]
  push:
jobs:
  one:
    runs-on: ubuntu-latest
    steps: 
      - name: Dump github context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump RUNNER context
        env: 
          RUNNER_CONTEXT: ${{ toJson(github) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump STEPS context
        env: 
          STEPS_CONTEXT: ${{ toJson(github) }}
        run: echo "$STEPS_CONTEXT"
      - name: dump TEST_SECRET
        run: echo ${{ secrets.TEST_SECRET }}
      - name: dump TEST_SECRET
        run: echo ${{ TEST_SECRET }}