name: hello world
on:
  repository_dispatch:
    types: [build]
  push:
    paths:
       - '!docs/**'
       - '**.go'
    branches: [main]
  pull_request:
    type: [opened, reopened,synchronize,labeled,unlabeled]
  workflow_dispatch:
jobs:
  Setup-golang:  
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env}}
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go version
      - run: go env -w GO111MODULE=off
      - run: go get -u github.com/helloyi/go-sshclient
      - run: go run 'docs/hello_world.go'

