name: hello world
on:
  push:
    paths:
      # - '!docs/**'
      # - '**.go'
    branches: [main]
  pull_request:
    type: [opened, reopened,synchronize,labeled,unlabeled]
  workflow_dispatch:
jobs:
  Setup-golang:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go version
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go env -w GO111MODULE=off
      - run: go run 'docs/hello_world.go'