name: hello world
on:
  push:
    paths:
      # - '!docs/**'
      # - '**.go'
    branches: [main]
  pull_request:
    type: [opened, reopened,synchronize,labeled,unlabeled]
  workflow_dispatch:
jobs:
  say-hello: 
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World 
      - run: echo "TODAY is $(date)" 
      - run: echo Heello world. $date
  Setup-golang:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go version
      - run: go run 'docs/**.go'